
services:
  ingest:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: rag-chat-backend:latest
    container_name: rag_ingest
    command: ["python", "/app/ingest/ingest.py"]
    env_file: .env
    volumes:
      - ${PWD}/docs:/app/docs:ro
    working_dir: /app/ingest
    restart: "no"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: rag-chat-backend:latest
    container_name: rag_backend
    env_file: .env
    expose:
      - "8000"
    depends_on:
      ingest:
        condition: service_completed_successfully
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rag-chat-frontend:latest
    container_name: rag_frontend
    ports:
      - "5173:80"   # 浏览器访问 http://localhost:5173
    depends_on:
      - backend
    restart: unless-stopped