# Namespace for RAG Chat App
apiVersion: v1
kind: Namespace
metadata:
  name: rag-chat-app
  labels:
    app: rag-chat-app
    version: v1.0.0
---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-chat-config
  namespace: rag-chat-app
data:
  PINECONE_INDEX_NAME: "default-index"
  EMBEDDING_MODEL: "text-embedding-3-small"
  AI_AGENT_NAME: "AUV"
  OPENAI_MODEL: "gpt-4o-mini"
---
# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: rag-chat-app
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        upstream backend {
            server rag-chat-backend:8000;
        }
        
        server {
            listen 80;
            server_name localhost;
            
            # Frontend static files
            location / {
                root /usr/share/nginx/html;
                try_files $uri $uri/ /index.html;
            }
            
            # API proxy to backend
            location /api/ {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # SSE support for streaming
                proxy_buffering off;
                proxy_cache off;
                proxy_set_header Connection '';
                proxy_http_version 1.1;
                chunked_transfer_encoding off;
            }
            
            # Health check
            location /health {
                proxy_pass http://backend/health;
            }
        }
    }