# Secrets for API keys
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: rag-chat-app
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded keys
  # echo -n "your-openai-api-key" | base64
  OPENAI_API_KEY: ""
  # echo -n "your-pinecone-api-key" | base64  
  PINECONE_API_KEY: ""
---
# PersistentVolumeClaim for file uploads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: rag-chat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard # Change based on your cluster's storage class
---
# PersistentVolumeClaim for database files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: rag-chat-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard